name: Deploy to Firebase Hosting on Semantic Version Tag

on:
  push:
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'   # major.minor.patch (e.g., 1.2.3)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - uses: actions/checkout@latest

      - name: Use Node.js
        uses: actions/setup-node@latest
        with:
          node-version-file: '.nvmrc'   # or specify a string like '20.x'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
            
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@latest
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{secrets.PROJECT_ID}}
